name: Update UCA MV Calendar

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # pas de token ici → utilise GITHUB_TOKEN automatiquement

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: |
          pip install --upgrade pip
          pip install requests icalendar pytz

      - name: Lancer le script
        run: python update_calendar.py

      - name: Commit et Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add uca_mv_filtered.ics
          git commit -m "Mise à jour automatique du calendrier" || echo "Pas de changement"
          git push
